version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - goos:
      - linux
    goarch:
      - amd64
      #- arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    include:
      - "^feat:"
      - "^fix:"
