version: 1

builds:
  - goos:
      - windows
    goarch:
      - amd64

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    include:
      - "^feat:"
      - "^fix:"
