blank_issues_enabled: false

contact_links:
  - name: Ideas
    url: https://github.com/getseabird/seabird/discussions
    about: Please submit ideas on our discussion forum.
  - name: Help
    url: https://github.com/getseabird/seabird/discussions
    about: Please submit help requests on our discussion forum.
