FROM mcr.microsoft.com/devcontainers/go:1-1.21-bookworm

RUN apt update && apt install -y cmake libfontconfig1-dev gcc pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev libgtk-4-dev libgirepository1.0-dev libgraphene-1.0-dev dbus-x11 libgl1-mesa-dev xorg-dev libadwaita-1-dev libnotify-bin