name: msys2

on:
  pull_request:
  push:

jobs:
  msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up msys
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          install: |
            mingw-w64-x86_64-gcc 
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-gtk4
            mingw-w64-x86_64-libadwaita
            mingw-w64-x86_64-gtksourceview5
            mingw-w64-x86_64-gobject-introspection
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Build
        run: |
          go build main.go
